stages:
        - build
        - test
        - deploy

Compile:
        when: always
        default:
                image: ubuntu:20.4
        stage: build
        script:
                - echo "Hello i am build"
Style:
        when: always
        stage: test
        script:
                - echo "Hello test"
Prodaction:
        when: always
        stage: deploy
        script:
                - echo "Hello deploy"
