stages:
        - build
        - test
        - integer
        - deploy

Compile:
        tags:
                - project
        when: always
        image: ubuntu:latest
        stage: build
        script:
                - make -C src/SimpleBash/cat s21_cat
                - make -C src/SimpleBash/grep s21_grep
        artifacts:
                paths:
                        - src/SimpleBash/cat/s21_cat
                        - src/SimpleBash/grep/s21_grep
                expire_in: 30 days

Style:
        tags:
                - project
        when: on_success
        stage: test
        script:
                - make -C src/SimpleBash/cat lint
                - make -C src/SimpleBash/grep lint

IntegralTest:
        tags:
                - project
        when: on_success
        stage: integer
        script:
                - make -C src/SimpleBash/cat test
                #- make -C src/SimpleBash/grep test
                - cd src/SimpleBash/grep
                - ./grep.sh
                - cd -


Production:
        tags:
                - project
        when: on_success
        stage: deploy
        script:

                - echo "Hello deploy"
