stages:
        - build
        - test
        - integer
        - deploy

Compile:
        tags:
                - test
        when: always
        image: ubuntu:latest
        stage: build
        script:
                - make -C src/SimpleBash/cat s21_cat
                - make -C src/SimpleBash/grep s21_grep
        artifacts:
                paths:
                        - src/SimpleBash/cat/s21_cat
                        - src/SimpleBash/grep/s21_grep
                expire_in: 30 days

Style:
        tags:
                - test
        when: on_success
        stage: test
        script:
                - make -C src/SimpleBash/cat lint
                - make -C src/SimpleBash/grep lint

IntegralTest:
        tags:
                - test
        when: on_success
        stage: integer
        script:
                - make -C src/SimpleBash/cat test
                - cd src/SimpleBash/grep
                - chmod +x grep.sh
                - ./grep.sh
                - cd -


Production:
        tags:
                - test
        when: on_success
        stage: deploy
        script:
                - scp src/SimpleBash/grep/s21_grep root@192.168.0.2:/home/mammiemi
                - scp src/SimpleBash/cat/s21/cat root@192.168.0.2:/home/mammiemi