stages:
        - build
        - test
        - integer
        - deploy

Compile:
        when: always
        image: ubuntu:latest
        stage: build
        script:
                - make -C src/SimpleBash/cat s21_cat
                - make -C src/SimpleBash/grep s21_grep
        artifacts:
                paths:
                        - src/cat/s21_cat
                        - src/grep/s21_grep
                expire_in: 30 days

Style:
        when: always
        stage: test
        script:
                - make -C src/SimpleBash/cat lint
                - make -C src/SimpleBash/grep lint

IntegralTest:
        when: always
        stage: integer
        script:
                - make -C src/SimpleBash/cat test
                - make -C src/SimpleBash/grep test


Prodaction:
        when: always
        stage: deploy
        script:
                - echo "Hello ddeploy"
